services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce_db
    volumes:
      - ./src/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/data
    ports:
      - "5432:5432"

  web:
    build:
      context: ./
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=src.app
      - FLASK_ENV=development
      - DB_HOST=db
      - DB_NAME=ecommerce_db
      - DB_USER=postgres
      - DB_PASS=postgres
